/*
    Question 2
    Student: Mirage Mohammad
 */
//Not using scanner for user interface so use args command
public class Q2FibonacciThread extends Thread {
    private int[] array;
    private int threshold;

    //Constructor
    Q2FibonacciThread(int[] array, int threshold)
    {
        this.array = array;
        this.threshold = threshold;
    }
    //Overriding the method run() from class Runnable
    @Override
    //Method run() generates the child threads
    public void run(){
        //Child Thread generating numbers
        for(int i = 2; i < threshold; i++){
            array[i] = array[i-1] + array[i-2];
        }
    }


    public static void main(String[] args){
        int[] myArray = new int[66];
        myArray[0] = 0;
        myArray[1] = 1;
        //Converting integer from the command line into an int
        int number = Integer.parseInt(args[0]);

        //Creating new child thread of fibonacci
        Q2FibonacciThread child = new Q2FibonacciThread(myArray, number);
        child.start();
        try {
            //Nothing
        }catch(Exception e){
            System.err.println(e);
        }
        //Parent Thread Printing the Numbers
        System.out.print("Fibonacci numbers are: ");
        //Basically parent thread outputs the sequence generated by the child
        for(int i =0; i<number; i++)
        {   if(i!=number-1)
                System.out.print(myArray[i] + ", ");
            else
                System.out.println(myArray[i] + " ");

        }
        System.out.println(" ");

    }



}
